# Generated by Django 6.0.2 on 2026-03-02 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_contact_options_alter_menuitem_restaurant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_owner',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('empresa', 'Empresa'), ('admin', 'Admin')], default='cliente', max_length=20),
        ),
    ]
