# Generated by Django 6.0.2 on 2026-03-04 00:04

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_profile_is_owner_profile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=myapp.models.menu_image_path),
        ),
    ]
